// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace EasyPeasy.API.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class EasyPeasyUserLoginResult
    {
        /// <summary>
        /// Initializes a new instance of the EasyPeasyUserLoginResult class.
        /// </summary>
        public EasyPeasyUserLoginResult()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the EasyPeasyUserLoginResult class.
        /// </summary>
        public EasyPeasyUserLoginResult(bool? success = default(bool?), string covenantToken = default(string))
        {
            Success = success;
            EasyPeasyToken = covenantToken;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "success")]
        public bool? Success { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "covenantToken")]
        public string EasyPeasyToken { get; set; }

    }
}
